name: Panic Report
description: The program panicked or was aborted
title: "[Panic]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thank you for helping improve lazyfetch!"

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "0.4.0"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      placeholder: "file:line:column"
    validations:
      required: false

  - type: input
    id: target
    attributes:
      label: Target
      placeholder: "Example: x86_64-linux-unknown"
    validations:
      required: true

  - type: textarea
    id: comment
    attributes:
      label: Additional comment
      description: Describe what could have caused the error.
    validations:
      required: false