[unstable]
build-std = ["core", "alloc", "std"]

[target.aarch64-linux-android]
linker = "/home/lukki/android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang"
rustflags = [
    "-C", "link-arg=-L/home/lukki/android/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/26",
]